### ISSUE TITLE
What order is guide run in?

### ISSUE THREAD

**Issue by spuder** [rancher/rodeo#13]
There are several guide readme's in this directory

https://github.com/rancher/rodeo/tree/master/guide

What order are the guides supposed to be executed?

**Comment by bashofmann** [comment]
This repository is now hosting a helm chart repository. A quickstart to setup Rancher can be found at https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/ and https://github.com/rancher/quickstart.
