### ISSUE TITLE
error: unable to recognize "nfs-client-provisioner.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by mihai-satmarean** [rancher/rodeo#14]
https://github.com/rancher/rodeo/blob/de304a3148754ddf1dd0cc826f244b9372367118/k8s/nfs-client-provisioner.yaml#L50

**Comment by bashofmann** [comment]
This repository is now hosting a helm chart repository. A quickstart to setup Rancher can be found at https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/ and https://github.com/rancher/quickstart.
