### ISSUE TITLE
Include libvirt/kvm terraform

### ISSUE THREAD

**Issue by blaggacao** [rancher/rodeo#9]
Who knows, maybe someone picks [this](https://gist.github.com/blaggacao/25d08af66b9678f07a35a95e6b71644f) up and helps poking on [this other issue](https://github.com/rancher/os/issues/2559). Else, please close.

**Comment by bashofmann** [comment]
This repository is now hosting a helm chart repository. A quickstart to setup Rancher can be found at https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/ and https://github.com/rancher/quickstart.
